### ISSUE TITLE
Feature: RTL support

### ISSUE THREAD

**Issue by ahangarha** [thepracticaldev/super-markdown#1]
Hi

One of the biggest problem of Markdown is its lake of RTL languages support. As the result, people need to include non MD codes withing their writings to make it RTL.

Please consider this feature.

All the bests

**Comment by caraya** [comment]
I agree that it's an issue but wouldn't it be better resolved in CSS rather than Markdown?

**Comment by ahangarha** [comment]
Maybe this is a good approach. Yet, i am not sure if it would work in all
cases.

**Comment by caraya** [comment]
Now knowing what your specific use cases are I can't comment on how well my approach would work.

**Comment by ahangarha** [comment]
When we write text in RTL languages, logically things should be placed in RTL mode. But there are cases we face problem. For example in most of the cases, code should be LTR (since rarely there is any thing written RTL and should be wrapped in `pre` or `code` tag, but we cannot ignore it. Or there are cases a sentence starts with English word and the program thinks it is LTR document while only the first word was English.

Now, we (RTL people) having problem with writting RTL in github and we hack it by adding `<div dir='rtl'>` at the first line. Still we need to hack it more to keep some part LTR and some other parts RTL. Until there be no provision in MarkDown standard for such cases, and we put the responsiblity to the converter to handle the situation, we will face with such issues.

I understand that we don't want to make MD complex. It needs to remain simple and with as minimum as possible tags. I just explain the problem with RTL.

I hope I could explain the issue well.

**Comment by caraya** [comment]
The default direction should be set in the HTML element and overridden where needed so I don't see where adding it in Markdown would change that.  

For the Github problem, a partial solution that works in Firefox is to set a user stylesheet that overrides the direction. Instructions for how to do this are here: https://davidwalsh.name/firefox-user-stylesheet

Unfortunately, this is a Firefox-only solution.

**Comment by ahangarha** [comment]
Since I have nothing more to propose, I think this issue should be closed.

Actually many other websites such as Gitlab are handling RTL relatively well. I don't know why github is not solving the issue despite many old requests (the common issue with all non FOSS services and software is that you should beg and still it is highly possible you don't get response)

I thought there might be some solution in MD itself but I guess the solution is rendering MD into HTML.

Thanks
